apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-generator
  template:
    metadata:
      labels:
        app: log-generator
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
      containers:
      - name: app
        image: busybox:1.37
        command:
        - /bin/sh
        - -c
        args:
        - |
          count=0
          while true; do
            count=$((count + 1))
            if [ $((count % 10)) -eq 0 ]; then
              printf '{"count":%d,"message":"stack trace example\\nError: something failed\\n  at main (app.js:42)\\n  at run (app.js:10)","ts":"%s"}\n' \
                "$count" "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
            else
              echo "{\"count\":$count,\"message\":\"hello from log-generator\",\"ts\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\"}"
            fi
            sleep 1
          done
